[package]
name = "password_protected"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-ini = "0.17"
argon2 = "0.4"
rand_core = { version = "0.6", features = ["std"] }
